pub struct ThemeRendition {
    artwork_status: i64,
    blend_mode: i32,
    color_space_id: u64,
    exif_orientation: i32,
    key: *mut coreui::rendition::RenditionKeyToken,
    name: String,
    opacity: f64,
    physical_size_in_meters: coregraphics::Size,
    properties: HashMap<String, String>,
    rendition_flags: cuithemerenditionrenditionflags,
    scale: u32,
    src_data: Vec<u8>,
    stack_key: coreui::rendition::RenditionKeyToken,
    subtype: u32,
    template_rendering_mode: i64,
    rendition_type: i64,
    uncropped_image: *mut coregraphics::Image,
    uti_type: String,
    valid_look_gradation: i64,
}